#!/usr/bin/env Rscript

# dbRDA plots and permutation tests for filtered untargeted metabolite features.
# Uses existing organism-specific output folders generated by
# untargeted_metabolite_pseudomonas_analysis.R.

options(stringsAsFactors = FALSE)

PROJECT_DIR <- Sys.getenv("PROJECT_DIR", "/Users/mingfeichen/Recyc_necromass")
OUT_DIR <- Sys.getenv("DBRDA_OUT_DIR", file.path(PROJECT_DIR, "outputs", "untargeted_metabolites_dbRDA"))
AEROBIC_ONLY <- tolower(Sys.getenv("AEROBIC_ONLY", "TRUE")) %in% c("1", "true", "t", "yes", "y")

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(readr)
  library(ggplot2)
  library(ggrepel)
  library(vegan)
})

dir.create(OUT_DIR, recursive = TRUE, showWarnings = FALSE)

datasets <- tibble::tribble(
  ~organism, ~input_dir,
  "Pseudomonas", file.path(PROJECT_DIR, "outputs", "untargeted_metabolites_pseudomonas"),
  "Arthrobacter", file.path(PROJECT_DIR, "outputs", "untargeted_metabolites_arthrobacter")
)

theme_dbrda <- function(base_size = 11) {
  theme_bw(base_size = base_size) +
    theme(
      panel.grid = element_blank(),
      legend.position = "right",
      plot.title = element_text(face = "bold", size = rel(1.18)),
      strip.background = element_rect(fill = "grey94", color = "grey70")
    )
}

parse_sample_names <- function(cols) {
  tibble(column = cols) %>%
    mutate(
      sample_id = str_remove(column, "\\.mzML Peak height$"),
      sample_id = str_remove(sample_id, "^\\d+_"),
      sample_id = str_remove(sample_id, "__.*$"),
      replicate = as.integer(str_match(sample_id, "_([0-9]+)$")[, 2]),
      condition = str_remove(sample_id, "_[0-9]+$")
    ) %>%
    separate(
      condition,
      into = c("treatment", "carbon", "organism", "oxygen_raw", "source", "day", "inoculation"),
      sep = "-",
      remove = FALSE,
      fill = "right",
      extra = "merge"
    ) %>%
    mutate(
      is_control = treatment == "ExCtrl" | carbon == "noC" | str_detect(condition, "ExCtrl|noC"),
      is_experimental = !is_control,
      oxygen = case_when(
        oxygen_raw == "A" ~ "Aerobic",
        oxygen_raw == "Ana" ~ "Anaerobic",
        TRUE ~ "Control"
      ),
      day = factor(day, levels = c("d0", "d2", "d6", "d11", "d27"), ordered = TRUE),
      day_num = as.numeric(str_remove(as.character(day), "^d")),
      source = factor(source, levels = c("fresh", "recyc", "na")),
      source_label = recode(as.character(source), fresh = "Fresh", recyc = "Recycled", na = "NA"),
      group_id = paste(treatment, carbon, organism, oxygen_raw, source, day, inoculation, sep = "-")
    )
}

scale_arrows <- function(site_scores, arrow_scores) {
  if (nrow(arrow_scores) == 0) return(arrow_scores)
  x_ratio <- max(abs(site_scores$CAP1), na.rm = TRUE) / max(abs(arrow_scores$CAP1), na.rm = TRUE)
  y_ratio <- max(abs(site_scores$CAP2), na.rm = TRUE) / max(abs(arrow_scores$CAP2), na.rm = TRUE)
  scale_factor <- 0.75 * min(x_ratio, y_ratio, na.rm = TRUE)
  if (!is.finite(scale_factor)) scale_factor <- 1
  arrow_scores %>%
    mutate(CAP1 = CAP1 * scale_factor, CAP2 = CAP2 * scale_factor)
}

tidy_anova <- function(anova_obj, organism, sheet, test_type) {
  df <- as.data.frame(anova_obj)
  variance_col <- intersect(c("Variance", "SumOfSqs", "ChiSquare"), names(df))[1]
  f_col <- intersect(c("F", "F.Model"), names(df))[1]
  p_col <- intersect(c("Pr(>F)", "Pr(>Chi)"), names(df))[1]

  df %>%
    tibble::rownames_to_column("term") %>%
    as_tibble() %>%
    transmute(
      organism,
      sheet,
      test_type,
      term,
      df = Df,
      variance = if (!is.na(variance_col)) .data[[variance_col]] else NA_real_,
      f_statistic = if (!is.na(f_col)) .data[[f_col]] else NA_real_,
      p_value = if (!is.na(p_col)) .data[[p_col]] else NA_real_
    )
}

make_dbrda <- function(organism_name, input_dir, sheet_name) {
  message("dbRDA: ", organism_name, " / ", sheet_name)
  peak_path <- file.path(input_dir, paste0(sheet_name, "_filtered_peak_heights.csv"))
  if (!file.exists(peak_path)) {
    warning("Missing filtered table: ", peak_path)
    return(NULL)
  }

  filtered <- read_csv(peak_path, show_col_types = FALSE)
  sample_cols <- names(filtered)[str_detect(names(filtered), "\\.mzML Peak height$")]
  sample_meta <- parse_sample_names(sample_cols) %>%
    filter(
      is_experimental,
      inoculation == "inoc",
      as.character(day) != "d0",
      source %in% c("fresh", "recyc"),
      if (AEROBIC_ONLY) oxygen == "Aerobic" else oxygen %in% c("Aerobic", "Anaerobic")
    ) %>%
    mutate(
      source = droplevels(source),
      source_label = factor(source_label, levels = c("Fresh", "Recycled")),
      oxygen = factor(oxygen, levels = if (AEROBIC_ONLY) c("Aerobic") else c("Aerobic", "Anaerobic")),
      day = droplevels(day),
      day_num = as.numeric(day_num)
    )

  if (nrow(sample_meta) < 6) {
    warning("Not enough selected samples for dbRDA: ", organism_name, " / ", sheet_name)
    return(NULL)
  }

  feature_meta <- filtered %>%
    transmute(
      feature_id = paste0("ID", `row ID`, "_mz", signif(`row m/z`, 6), "_rt", signif(`row retention time`, 4)),
      row_id = `row ID`,
      mz = `row m/z`,
      retention_time = `row retention time`
    )

  mat <- t(as.matrix(filtered[, sample_meta$column, drop = FALSE]))
  storage.mode(mat) <- "numeric"
  mat[is.na(mat)] <- 0
  mat <- log1p(mat)
  mat <- mat[, colSums(mat) > 0, drop = FALSE]

  cap_formula <- if (AEROBIC_ONLY) {
    mat ~ source + day_num
  } else {
    mat ~ source + oxygen + day_num
  }
  cap <- capscale(cap_formula, data = sample_meta, distance = "bray")
  cap_eig <- cap$CCA$eig
  axis_pct <- if (length(cap_eig) >= 2) {
    round(100 * cap_eig[1:2] / sum(cap_eig), 1)
  } else {
    c(NA_real_, NA_real_)
  }

  site_scores <- as.data.frame(scores(cap, display = "sites", choices = 1:2)) %>%
    as_tibble() %>%
    setNames(c("CAP1", "CAP2")) %>%
    bind_cols(sample_meta)

  bp <- as.data.frame(scores(cap, display = "bp", choices = 1:2)) %>%
    tibble::rownames_to_column("variable") %>%
    as_tibble() %>%
    setNames(c("variable", "CAP1", "CAP2")) %>%
    mutate(
      variable_label = recode(
        variable,
        sourcerecyc = "Source: recycled",
        day_num = "Time (day)",
        .default = variable
      )
    )
  arrow_scores <- scale_arrows(site_scores, bp)

  overall <- anova.cca(cap, permutations = 999)
  terms <- anova.cca(cap, by = "terms", permutations = 999)
  margin <- anova.cca(cap, by = "margin", permutations = 999)
  anova_tbl <- bind_rows(
    tidy_anova(overall, organism_name, sheet_name, "overall"),
    tidy_anova(terms, organism_name, sheet_name, "terms"),
    tidy_anova(margin, organism_name, sheet_name, "margin")
  )

  rsq <- RsquareAdj(cap)
  model_tbl <- tibble(
    organism = organism_name,
    sheet = sheet_name,
    samples = nrow(sample_meta),
    features = ncol(mat),
    constrained_inertia = cap$CCA$tot.chi,
    total_inertia = cap$tot.chi,
    constrained_fraction = cap$CCA$tot.chi / cap$tot.chi,
    r2 = rsq$r.squared,
    r2_adjusted = rsq$adj.r.squared,
    cap1_constrained_pct = axis_pct[1],
    cap2_constrained_pct = axis_pct[2]
  )

  p <- ggplot(site_scores, aes(CAP1, CAP2)) +
    geom_hline(yintercept = 0, linetype = "dotted", color = "grey55") +
    geom_vline(xintercept = 0, linetype = "dotted", color = "grey55") +
    geom_point(
      aes(color = source_label, shape = day),
      size = 3.2,
      alpha = 0.9,
      stroke = 0.7
    ) +
    geom_segment(
      data = arrow_scores,
      aes(x = 0, y = 0, xend = CAP1, yend = CAP2),
      inherit.aes = FALSE,
      arrow = arrow(length = unit(0.2, "cm")),
      color = "grey25",
      linewidth = 0.55
    ) +
    geom_text_repel(
      data = arrow_scores,
      aes(CAP1, CAP2, label = variable_label),
      inherit.aes = FALSE,
      size = 4.2,
      min.segment.length = 0,
      seed = 12
    ) +
    scale_color_manual(values = c("Fresh" = "#2166AC", "Recycled" = "#D7191C")) +
    scale_shape_manual(values = c("d2" = 21, "d6" = 22, "d11" = 24, "d27" = 25)) +
    labs(
      title = paste0(organism_name, " ", sheet_name, if (AEROBIC_ONLY) " aerobic-only dbRDA (Bray-Curtis)" else " dbRDA (Bray-Curtis)"),
      subtitle = paste0(
        "Permutation tests from capscale; constrained fraction = ",
        sprintf("%.1f", 100 * model_tbl$constrained_fraction), "%"
      ),
      x = paste0("CAP1 (", axis_pct[1], "% constrained variance)"),
      y = paste0("CAP2 (", axis_pct[2], "% constrained variance)"),
      color = "Source",
      shape = "Day"
    ) +
    coord_equal() +
    theme_dbrda(base_size = 12)

  prefix <- paste0(tolower(organism_name), "_", sheet_name, "_dbrda_bray", if (AEROBIC_ONLY) "_aerobic_only" else "")
  ggsave(file.path(OUT_DIR, paste0(prefix, ".pdf")), p, width = 9.5, height = 6.8, units = "in")
  ggsave(file.path(OUT_DIR, paste0(prefix, ".png")), p, width = 9.5, height = 6.8, units = "in", dpi = 300)

  write_csv(site_scores, file.path(OUT_DIR, paste0(prefix, "_site_scores.csv")))
  write_csv(arrow_scores, file.path(OUT_DIR, paste0(prefix, "_arrows.csv")))
  write_csv(anova_tbl, file.path(OUT_DIR, paste0(prefix, "_permutation_tests.csv")))
  write_csv(model_tbl, file.path(OUT_DIR, paste0(prefix, "_model_summary.csv")))

  list(model = model_tbl, tests = anova_tbl)
}

results <- list()
for (i in seq_len(nrow(datasets))) {
  for (sheet_name in c("positive", "negative")) {
    key <- paste(datasets$organism[i], sheet_name, sep = "_")
    results[[key]] <- make_dbrda(datasets$organism[i], datasets$input_dir[i], sheet_name)
  }
}

model_summary <- bind_rows(lapply(results, `[[`, "model"))
permutation_tests <- bind_rows(lapply(results, `[[`, "tests"))

write_csv(model_summary, file.path(OUT_DIR, "combined_dbrda_model_summary.csv"))
write_csv(permutation_tests, file.path(OUT_DIR, "combined_dbrda_permutation_tests.csv"))

message("Wrote dbRDA outputs to: ", OUT_DIR)
